### PR TITLE
2013 player + webm-based uploader

### PR DESCRIPTION
**Pull request by chaziz94**
a prototype.

### CODE REVIEW

**Review by forkiesassds — CHANGES_REQUESTED** [review]
let's not do this.

**Comment by chaziz94** [comment]
icty, it’s that, or mpeg-dash hell

reminder: you were okay with the 2012 player on poktube

**Comment by chaziz94** [comment]
idea: make 2013 player optional

**Comment by chaziz94** [comment]
image

it's fucked

**Comment by chaziz94** [comment]
i'll make a new branch

**Pull request closed without merging**
